import { Module } from '@nestjs/common';
import { InternalAiAssistantService } from './assistant';
import {
  AiCapabilityRegistryService,
  AiCapabilityRoutingService,
  builtInAiCapabilities,
} from './capabilities';
import {
  AI_AUTHORIZATION_PROVIDER,
  AI_AUDIT_PROVIDER,
  AI_CAPABILITY_DEFINITIONS,
  AI_CONVERSATION_DEFINITIONS,
  AI_CONTEXT_PROVIDERS,
  AI_GATEWAY,
  AI_GATEWAY_EXTENSIONS,
  AI_GATEWAY_LIFECYCLE_HOOKS,
  AI_GATEWAY_MIDDLEWARE,
  AI_GATEWAY_PIPELINE_STAGES,
  AI_MCP_PROMPTS,
  AI_MCP_RESOURCES,
  AI_MCP_TOOLS,
  AI_MCP_TRANSPORTS,
  AI_PROMPT_DEFINITIONS,
  AI_PROMPT_PROVIDER,
  AI_PROVIDER_ADAPTERS,
  AI_SKILL_DEFINITIONS,
  AI_SKILLS,
  AI_TELEMETRY_PROVIDER,
  AIEventBusService,
  AiConfigService,
  AiLoggerService,
} from './common';
import {
  ConversationPlannerService,
  ConversationRegistryService,
  ConversationSessionRegistryService,
  builtInConversationDefinitions,
} from './conversation';
import {
  AiExecutionCoordinator,
  AiExecutionEngineService,
  AiExecutionStateMachineService,
} from './execution';
import {
  AiContextAggregationService,
  AiContextRegistryService,
  CalendarContextProvider,
  ContextProvider,
  DocumentContextProvider,
  PortfolioContextProvider,
  ProjectContextProvider,
  RaidContextProvider,
  TaskContextProvider,
  TeamContextProvider,
  WorkspaceContextProvider,
} from './context';
import { AiGatewayService } from './gateway';
import {
  AiAuditStage,
  AiAuthenticationHookStage,
  AiAuthorizationHookStage,
  AiCapabilityResolutionStage,
  AiContextAssemblyPlaceholderStage,
  AiExecutionContextEnrichmentStage,
  AiPipelineEngineService,
  AiPipelineStage,
  AiPromptResolutionPlaceholderStage,
  AiProviderDispatchPlaceholderStage,
  AiRequestValidationStage,
  AiResponseNormalizationStage,
  AiStageRegistryService,
  AiTelemetryStage,
} from './gateway/pipeline';
import {
  McpGatewayDelegationService,
  McpPromptRegistryService,
  McpResourceRegistryService,
  McpServerLifecycleService,
  McpSessionManagerService,
  McpSessionRegistryService,
  McpToolRegistryService,
  McpTransportRegistryService,
} from './mcp';
import {
  AIHttpClient,
  APIKeyAuthenticationProvider,
  AiProviderRegistryService,
  AiProviderRoutingService,
  MockAiProviderAdapter,
  OpenAIErrorMapper,
  OpenAIProviderAdapter,
  OpenAIRequestMapper,
  OpenAIResponseMapper,
} from './providers';
import { AiPlaygroundService } from './playground';
import {
  AiPromptRegistryService,
  AiPromptResolutionEngineService,
  builtInPromptDefinitions,
} from './prompts';
import {
  AiSkillDependencyGraphService,
  AiSkillRegistryService,
  AiSkillResolutionService,
  builtInSkillDefinitions,
} from './skills';

const pipelineStageProviders = [
  AiRequestValidationStage,
  AiAuthenticationHookStage,
  AiAuthorizationHookStage,
  AiExecutionContextEnrichmentStage,
  AiCapabilityResolutionStage,
  AiContextAssemblyPlaceholderStage,
  AiPromptResolutionPlaceholderStage,
  AiProviderDispatchPlaceholderStage,
  AiResponseNormalizationStage,
  AiTelemetryStage,
  AiAuditStage,
];

const contextProviderClasses = [
  ProjectContextProvider,
  TaskContextProvider,
  DocumentContextProvider,
  RaidContextProvider,
  TeamContextProvider,
  CalendarContextProvider,
  PortfolioContextProvider,
  WorkspaceContextProvider,
];

const placeholderProviders = [
  { provide: AI_AUTHORIZATION_PROVIDER, useValue: null },
  { provide: AI_AUDIT_PROVIDER, useValue: null },
  { provide: AI_CAPABILITY_DEFINITIONS, useValue: builtInAiCapabilities },
  {
    provide: AI_CONVERSATION_DEFINITIONS,
    useValue: builtInConversationDefinitions,
  },
  {
    inject: contextProviderClasses,
    provide: AI_CONTEXT_PROVIDERS,
    useFactory: (...providers: ContextProvider[]) => providers,
  },
  { provide: AI_GATEWAY, useExisting: AiGatewayService },
  { provide: AI_GATEWAY_EXTENSIONS, useValue: [] },
  { provide: AI_GATEWAY_LIFECYCLE_HOOKS, useValue: [] },
  { provide: AI_GATEWAY_MIDDLEWARE, useValue: [] },
  {
    inject: pipelineStageProviders,
    provide: AI_GATEWAY_PIPELINE_STAGES,
    useFactory: (...stages: AiPipelineStage[]) => stages,
  },
  { provide: AI_MCP_PROMPTS, useValue: [] },
  { provide: AI_MCP_RESOURCES, useValue: [] },
  { provide: AI_MCP_TOOLS, useValue: [] },
  { provide: AI_MCP_TRANSPORTS, useValue: [] },
  { provide: AI_PROMPT_DEFINITIONS, useValue: builtInPromptDefinitions },
  { provide: AI_PROMPT_PROVIDER, useValue: null },
  {
    inject: [MockAiProviderAdapter, OpenAIProviderAdapter],
    provide: AI_PROVIDER_ADAPTERS,
    useFactory: (
      mockProvider: MockAiProviderAdapter,
      openaiProvider: OpenAIProviderAdapter,
    ) => [mockProvider, openaiProvider],
  },
  { provide: AI_SKILL_DEFINITIONS, useValue: builtInSkillDefinitions },
  { provide: AI_SKILLS, useValue: [] },
  { provide: AI_TELEMETRY_PROVIDER, useValue: null },
];

@Module({
  providers: [
    AiConfigService,
    AIEventBusService,
    AiLoggerService,
    AiGatewayService,
    AiCapabilityRegistryService,
    AiCapabilityRoutingService,
    ConversationPlannerService,
    ConversationRegistryService,
    ConversationSessionRegistryService,
    AiExecutionCoordinator,
    AiExecutionEngineService,
    AiExecutionStateMachineService,
    AiContextAggregationService,
    AiContextRegistryService,
    AiPipelineEngineService,
    AiStageRegistryService,
    AiProviderRegistryService,
    AiProviderRoutingService,
    AIHttpClient,
    APIKeyAuthenticationProvider,
    OpenAIErrorMapper,
    OpenAIProviderAdapter,
    OpenAIRequestMapper,
    OpenAIResponseMapper,
    AiPlaygroundService,
    AiPromptRegistryService,
    AiPromptResolutionEngineService,
    AiSkillDependencyGraphService,
    AiSkillRegistryService,
    AiSkillResolutionService,
    McpGatewayDelegationService,
    McpPromptRegistryService,
    McpResourceRegistryService,
    McpServerLifecycleService,
    McpSessionManagerService,
    McpSessionRegistryService,
    McpToolRegistryService,
    McpTransportRegistryService,
    InternalAiAssistantService,
    MockAiProviderAdapter,
    ...pipelineStageProviders,
    ...contextProviderClasses,
    ...placeholderProviders,
  ],
  exports: [
    AiConfigService,
    AIEventBusService,
    AiLoggerService,
    AiGatewayService,
    AiCapabilityRegistryService,
    AiCapabilityRoutingService,
    ConversationPlannerService,
    ConversationRegistryService,
    ConversationSessionRegistryService,
    AiExecutionCoordinator,
    AiExecutionEngineService,
    AiExecutionStateMachineService,
    AiContextAggregationService,
    AiContextRegistryService,
    AiPipelineEngineService,
    AiStageRegistryService,
    AiProviderRegistryService,
    AiProviderRoutingService,
    AIHttpClient,
    APIKeyAuthenticationProvider,
    OpenAIErrorMapper,
    OpenAIProviderAdapter,
    OpenAIRequestMapper,
    OpenAIResponseMapper,
    AiPlaygroundService,
    AiPromptRegistryService,
    AiPromptResolutionEngineService,
    AiSkillDependencyGraphService,
    AiSkillRegistryService,
    AiSkillResolutionService,
    McpGatewayDelegationService,
    McpPromptRegistryService,
    McpResourceRegistryService,
    McpServerLifecycleService,
    McpSessionManagerService,
    McpSessionRegistryService,
    McpToolRegistryService,
    McpTransportRegistryService,
    InternalAiAssistantService,
    ...placeholderProviders,
  ],
})
export class AiModule {}
