export const AI_AUTHORIZATION_PROVIDER = Symbol('AI_AUTHORIZATION_PROVIDER');
export const AI_AUDIT_PROVIDER = Symbol('AI_AUDIT_PROVIDER');
export const AI_CAPABILITY_DEFINITIONS = Symbol('AI_CAPABILITY_DEFINITIONS');
export const AI_ENTERPRISE_CAPABILITY_DEFINITIONS = Symbol(
  'AI_ENTERPRISE_CAPABILITY_DEFINITIONS',
);
export const AI_EXECUTION_ENGINE = Symbol('AI_EXECUTION_ENGINE');
export const AI_CONVERSATION_DEFINITIONS = Symbol(
  'AI_CONVERSATION_DEFINITIONS',
);
export const AI_CONTEXT_PROVIDERS = Symbol('AI_CONTEXT_PROVIDERS');
export const AI_GATEWAY = Symbol('AI_GATEWAY');
export const AI_GATEWAY_EXTENSIONS = Symbol('AI_GATEWAY_EXTENSIONS');
export const AI_GATEWAY_LIFECYCLE_HOOKS = Symbol('AI_GATEWAY_LIFECYCLE_HOOKS');
export const AI_GATEWAY_MIDDLEWARE = Symbol('AI_GATEWAY_MIDDLEWARE');
export const AI_GATEWAY_PIPELINE_STAGES = Symbol('AI_GATEWAY_PIPELINE_STAGES');
export const AI_MCP_PROMPTS = Symbol('AI_MCP_PROMPTS');
export const AI_MCP_RESOURCES = Symbol('AI_MCP_RESOURCES');
export const AI_MCP_TOOLS = Symbol('AI_MCP_TOOLS');
export const AI_MCP_TRANSPORTS = Symbol('AI_MCP_TRANSPORTS');
export const AI_PROMPT_DEFINITIONS = Symbol('AI_PROMPT_DEFINITIONS');
export const AI_PROMPT_PROVIDER = Symbol('AI_PROMPT_PROVIDER');
export const AI_PROVIDER_ADAPTERS = Symbol('AI_PROVIDER_ADAPTERS');
export const AI_SKILL_DEFINITIONS = Symbol('AI_SKILL_DEFINITIONS');
export const AI_SKILLS = Symbol('AI_SKILLS');
export const AI_TELEMETRY_PROVIDER = Symbol('AI_TELEMETRY_PROVIDER');
