import { EnterpriseCapabilityMetadata } from './enterprise-capability.types';

const projectContext = ['project', 'workspace'] as const;

export const builtInEnterpriseCapabilityDefinitions: EnterpriseCapabilityMetadata[] = [
  {
    allowedRoles: [],
    category: 'delivery',
    description: 'Prepare a structured daily stand-up review from project execution data.',
    displayName: 'AI Daily Review',
    executionCapabilityId: 'chat',
    icon: 'sparkles',
    id: 'daily-review-assistant',
    permissions: ['project.read'],
    requiredContext: ['project', 'task', 'execution', 'raid', 'team', 'workspace', 'user'],
    responseType: 'review',
    supportedSkills: ['daily-review-analysis'],
    version: '1.0.0',
    visibility: 'internal',
  },
  {
    allowedRoles: [],
    category: 'project',
    description: 'Summarize project delivery status and current execution context.',
    displayName: 'Project Summary',
    executionCapabilityId: 'chat',
    icon: 'file-chart-column',
    id: 'project-summary',
    permissions: ['project.read'],
    requiredContext: projectContext,
    responseType: 'executive-summary',
    supportedSkills: ['project-delivery-assistant'],
    version: '1.0.0',
    visibility: 'internal',
  },
  {
    allowedRoles: [],
    category: 'delivery',
    description: 'Review execution progress, blockers, and delivery attention areas.',
    displayName: 'Execution Review',
    executionCapabilityId: 'chat',
    icon: 'activity',
    id: 'execution-review',
    permissions: ['project.read'],
    requiredContext: [...projectContext, 'task', 'execution'],
    responseType: 'review',
    supportedSkills: ['project-delivery-assistant'],
    version: '1.0.0',
    visibility: 'internal',
  },
  {
    allowedRoles: [],
    category: 'governance',
    description: 'Review RAID exposure and surface governance attention areas.',
    displayName: 'RAID Review',
    executionCapabilityId: 'reasoning',
    icon: 'triangle-alert',
    id: 'raid-review',
    permissions: ['project.read', 'raid.read'],
    requiredContext: ['project', 'raid'],
    responseType: 'analysis',
    supportedSkills: ['raid-analysis-assistant'],
    version: '1.0.0',
    visibility: 'internal',
  },
  {
    allowedRoles: [],
    category: 'portfolio',
    description: 'Summarize portfolio health and projects requiring attention.',
    displayName: 'Portfolio Health Review',
    executionCapabilityId: 'structured-output',
    icon: 'briefcase-business',
    id: 'portfolio-health-review',
    permissions: ['portfolio.read'],
    requiredContext: ['portfolio', 'workspace'],
    responseType: 'structured-report',
    supportedSkills: ['portfolio-status-assistant'],
    version: '1.0.0',
    visibility: 'internal',
  },
];
